version: "3.8"

services:
  api:
    container_name: portfolio-api
    restart: unless-stopped
    image: portfolio-api
    build:
      context: api
      target: production
      dockerfile: dockerfile
    ports:
      - 8080:8080
    networks:
      - shared-network

  client:
    container_name: portfolio-client
    restart: unless-stopped
    image: portfolio-client
    build:
      context: client
      target: production
      dockerfile: Dockerfile
    ports:
      - 80:3000
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
